### ISSUE TITLE
[BUG] [ws-cleanup-tool] Errors starting tool with python 3.10.2 

### ISSUE THREAD

**Issue by tareks** [whitesource-ps/ws-cleanup-tool#33]
**Bug Description**  
We run the cleanup tool as part of a scheduled job in Azure Pipelines. This has worked fine up until 25/01/2022, but then started to fail with the following errors:

``` 
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.2/x64/bin/ws_cleanup_tool", line 5, in <module>
    from ws_cleanup_tool.cleanup_tool import main
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/ws_cleanup_tool/cleanup_tool.py", line 12, in <module>
    from ws_sdk import ws_errors, WS, ws_constants
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/ws_sdk/__init__.py", line 3, in <module>
    from ws_sdk.web import WS
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/ws_sdk/web.py", line 8, in <module>
    import requests_cache
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/requests_cache/__init__.py", line 43, in <module>
    from .backends import *
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/requests_cache/backends/__init__.py", line 8, in <module>
    from .base import BaseCache, BaseStorage
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/requests_cache/backends/base.py", line 18, in <module>
    from ..serializers import init_serializer
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/requests_cache/serializers/__init__.py", line 6, in <module>
    from .preconf import (
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/requests_cache/serializers/preconf.py", line 26, in <module>
    base_stage = CattrStage()  #: Base stage for all serializer pipelines
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/requests_cache/serializers/cattrs.py", line 32, in __init__
    self.converter = init_converter(factory)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/requests_cache/serializers/cattrs.py", line 67, in init_converter
    converter.register_structure_hook(
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/cattr/converters.py", line 269, in register_structure_hook
    self._structure_func.register_cls_list([(cl, func)])
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/cattr/dispatch.py", line 57, in register_cls_list
    self._single_dispatch.register(cls, handler)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/functools.py", line 856, in register
    raise TypeError(
TypeError: Invalid first argument to `register()`. ForwardRef('CachedResponse') is not a class
```

This appears to be related to an underlying Azure Pipelines agent (ubuntu-latest / 20.04) update from python 3.10.1 to 3.10.2. Perhaps an underlying python issue? 

**Steps to Reproduce**  

Sample pipeline tasks that we have that simulate the steps are:

```
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- bash: |
    pip install ws-cleanup-tool
    ws_cleanup_tool 
  displayName: 'Run Cleanup Tool'
```

These essentially;

1. Install latest python 3.x (3.10.2 at time of this writing)
2. Use pip to install ws-cleanup-tool
3. Run the cleanup tool using the `ws_cleanup_tool` command.

**Expected Behavior**  
Tool should start with at least the following (no config provided):

```
ws_cleanup_tool
ERROR 22-01-30 09:44:28 139835302979392 cleanup_tool: No configuration file found at: ../params.config
```
**Screenshots**  
See stacktrace above.

**Environment Details**  
 - Azure pipelines agent running (ubuntu-latest) ubuntu 20.04 (python 3.10.2)

**Additional Context**  

Seems like the current workaround is to pin python version to 3.7 which seems to get around this issue.  Unsure if this is solved with latest 3.10.x or not yet. Just posting in case someone else runs into the same issue.

**Comment by tamari-oz** [comment]
Hi,
I'm not sure why but in the stack I can see package: requests_cache which was removed in ws-sdk 0.8.2 (due to poor performance).
The latest ws-sdk that should be pulled is 0.9.0.3.

Can you please send the output of _pip freeze_?

**Comment by tareks** [comment]
With `Python 3.10.2 x64` and `3.9.10` (fails) the output is:

```
appdirs==1.4.4
attrs==21.4.0
cattrs==1.10.0
certifi==2021.10.8
charset-normalizer==2.0.11
configparser==5.2.0
DateTime==4.3
idna==3.3
pytz==2021.3
requests==2.26.0
requests-cache==0.8.1
six==1.16.0
url-normalize==1.4.3
urllib3==1.26.8
ws-cleanup-tool==0.2.1
ws-sdk==0.8.0.2
zope.interface==5.4.0
```

With `Python 3.8.12 x64` (works) as it does with 3.7, the output is:
```
appdirs==1.4.4
attrs==21.4.0
cattrs==1.10.0
certifi==2021.10.8
charset-normalizer==2.0.11
configparser==5.2.0
DateTime==4.3
idna==3.3
pytz==2021.3
requests==2.26.0
requests-cache==0.8.1
six==1.16.0
url-normalize==1.4.3
urllib3==1.26.8
ws-cleanup-tool==0.2.1
ws-sdk==0.8.0.2
zope.interface==5.4.0
```

**Comment by rammatzkvosky** [comment]
Hi @tareks  ,check our [latest version ( 0.2.2 )](https://pypi.org/project/ws-cleanup-tool/0.2.2/) - it should fix the reported error.
