### ISSUE TITLE
Problem running WS cleanup tool - Error message appear

### ISSUE THREAD

**Issue by Nova-Asif-s** [whitesource-ps/ws-cleanup-tool#68]
Hello Professional support team,

I'm trying to run the cleanup tool ( Joined session with Oksana ) and i'm getting below error message 
I'll appreciate assistance on this one

The user key and Org key have not been written in the case but they were added to original command

D:\CodeLegalityData\WhiteSource\ws-cleanup-tool-22.8.5\ws_cleanup_tool>python cleanup_tool.py -r 60
pdateTime -u <USER_KEY> -k <ORG_TOKEN>
c648a473a899a61102806e1fc
Traceback (most recent call last):
  File "cleanup_tool.py", line 8, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'

D:\CodeLegalityData\WhiteSource\ws-cleanup-tool-22.8.5\ws_cleanup_tool>

**Comment by rammatzkvosky** [comment]
Hi @Nova-Asif-s ,

Which python version are you running the script with ?

**Comment by Nova-Asif-s** [comment]
Hello
I've ran it with python-3.8.10-embed-amd64 version and experienced other issue :

The following error message appeared in VS CODE - Debug mode :

Exception has occurred: ModuleNotFoundError
No module named 'ws_sdk'
  File "C:\WhiteSource\ws-cleanup-tool-22.8.5\ws_cleanup_tool\cleanup_tool.py", line 14, in <module>
    from ws_sdk import ws_errors, WS, ws_constants

**Comment by tidharm** [comment]
@Nova-Asif-s, the error indicates your local environment is missing one of the dependencies ([ws-sdk](https://pypi.org/project/ws-sdk), in this case), which typically indicates an incorrect or otherwise unsuccessful installation.

Could you please confirm how did you install **ws-cleanp-tool**?

Was it [using `pip`](https://github.com/whitesource-ps/ws-cleanup-tool#installation-and-execution-from-pypi-recommended), or was it by [cloning it](https://github.com/whitesource-ps/ws-cleanup-tool#installation-and-execution-from-pypi-recommended) from GitHub?

If it's the latter, could you please confirm you executed the installation command `pip install -r requirements.txt`?
